### ISSUE TITLE
Mensa am Park shows wrong food

### ISSUE THREAD

**Issue by whosFritz** [greybaron/stuwe-telegram-rs#5]
When clicked on heute on saturdays it shows me monday but not saturday meals. Probably hardcoded monday to friday queries

https://github.com/greybaron/stuwe-telegram-rs/assets/97552289/193abd15-cfa5-464c-b3f4-b12f10919d3e

**Comment by fnschmidt** [comment]
Studentenwerk doesn't provide data for saturdays

**Comment by fnschmidt** [comment]
also charge your phone tyvm
